version: '2'
run:
  tests: false
  timeout: 10s
  concurrency: 4 # Run multiple linters in parallel (default is number of CPUs)
  modules-download-mode: readonly # Don't download modules, use go.mod cache
  build-tags: []

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - revive
    - staticcheck
    - tagalign
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errorlint:
      asserts: false
    funlen:
      lines: 120
      ignore-comments: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G101
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 300
    misspell:
      locale: US
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
    tagalign:
      order:
        - json
        - db
        - validate
      strict: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
    paths:
      - .*_templ\\.go$
      - third_party$
      - builtin$
      - examples$
      - ent/generated
      - cmd/*
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
  exclusions:
    generated: lax
    paths:
      - .*_templ\\.go$
      - third_party$
      - builtin$
      - examples$
      - ent/generated
      - cmd/*
