// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "column", Type: field.TypeString, Default: "backlog"},
		{Name: "assignee", Type: field.TypeString, Default: ""},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// TaskHistoriesColumns holds the columns for the "task_histories" table.
	TaskHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeString},
		{Name: "details", Type: field.TypeString, Nullable: true},
		{Name: "actor", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "task_history", Type: field.TypeInt},
	}
	// TaskHistoriesTable holds the schema information for the "task_histories" table.
	TaskHistoriesTable = &schema.Table{
		Name:       "task_histories",
		Columns:    TaskHistoriesColumns,
		PrimaryKey: []*schema.Column{TaskHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_histories_tasks_history",
				Columns:    []*schema.Column{TaskHistoriesColumns[5]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TaskTagsColumns holds the columns for the "task_tags" table.
	TaskTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "task_tags", Type: field.TypeInt},
	}
	// TaskTagsTable holds the schema information for the "task_tags" table.
	TaskTagsTable = &schema.Table{
		Name:       "task_tags",
		Columns:    TaskTagsColumns,
		PrimaryKey: []*schema.Column{TaskTagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_tags_tasks_tags",
				Columns:    []*schema.Column{TaskTagsColumns[4]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TasksTable,
		TaskHistoriesTable,
		TaskTagsTable,
	}
)

func init() {
	TaskHistoriesTable.ForeignKeys[0].RefTable = TasksTable
	TaskTagsTable.ForeignKeys[0].RefTable = TasksTable
}
