// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/j0hnsmith/botTaskTracker/ent/schema"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/taskhistory"
	"github.com/j0hnsmith/botTaskTracker/ent/tasktag"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[0].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescColumn is the schema descriptor for column field.
	taskDescColumn := taskFields[2].Descriptor()
	// task.DefaultColumn holds the default value on creation for the column field.
	task.DefaultColumn = taskDescColumn.Default.(string)
	// taskDescAssignee is the schema descriptor for assignee field.
	taskDescAssignee := taskFields[3].Descriptor()
	// task.DefaultAssignee holds the default value on creation for the assignee field.
	task.DefaultAssignee = taskDescAssignee.Default.(string)
	// taskDescPosition is the schema descriptor for position field.
	taskDescPosition := taskFields[4].Descriptor()
	// task.DefaultPosition holds the default value on creation for the position field.
	task.DefaultPosition = taskDescPosition.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[5].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[6].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskhistoryFields := schema.TaskHistory{}.Fields()
	_ = taskhistoryFields
	// taskhistoryDescAction is the schema descriptor for action field.
	taskhistoryDescAction := taskhistoryFields[0].Descriptor()
	// taskhistory.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	taskhistory.ActionValidator = taskhistoryDescAction.Validators[0].(func(string) error)
	// taskhistoryDescActor is the schema descriptor for actor field.
	taskhistoryDescActor := taskhistoryFields[2].Descriptor()
	// taskhistory.DefaultActor holds the default value on creation for the actor field.
	taskhistory.DefaultActor = taskhistoryDescActor.Default.(string)
	// taskhistoryDescCreatedAt is the schema descriptor for created_at field.
	taskhistoryDescCreatedAt := taskhistoryFields[3].Descriptor()
	// taskhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	taskhistory.DefaultCreatedAt = taskhistoryDescCreatedAt.Default.(func() time.Time)
	tasktagFields := schema.TaskTag{}.Fields()
	_ = tasktagFields
	// tasktagDescKey is the schema descriptor for key field.
	tasktagDescKey := tasktagFields[0].Descriptor()
	// tasktag.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	tasktag.KeyValidator = tasktagDescKey.Validators[0].(func(string) error)
	// tasktagDescValue is the schema descriptor for value field.
	tasktagDescValue := tasktagFields[1].Descriptor()
	// tasktag.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	tasktag.ValueValidator = tasktagDescValue.Validators[0].(func(string) error)
	// tasktagDescCreatedAt is the schema descriptor for created_at field.
	tasktagDescCreatedAt := tasktagFields[2].Descriptor()
	// tasktag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tasktag.DefaultCreatedAt = tasktagDescCreatedAt.Default.(func() time.Time)
}
