// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/j0hnsmith/botTaskTracker/ent/predicate"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/taskhistory"
)

// TaskHistoryUpdate is the builder for updating TaskHistory entities.
type TaskHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *TaskHistoryMutation
}

// Where appends a list predicates to the TaskHistoryUpdate builder.
func (_u *TaskHistoryUpdate) Where(ps ...predicate.TaskHistory) *TaskHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *TaskHistoryUpdate) SetAction(v string) *TaskHistoryUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableAction(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *TaskHistoryUpdate) SetDetails(v string) *TaskHistoryUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableDetails(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *TaskHistoryUpdate) ClearDetails() *TaskHistoryUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetActor sets the "actor" field.
func (_u *TaskHistoryUpdate) SetActor(v string) *TaskHistoryUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableActor(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *TaskHistoryUpdate) SetTaskID(id int) *TaskHistoryUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskHistoryUpdate) SetTask(v *Task) *TaskHistoryUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_u *TaskHistoryUpdate) Mutation() *TaskHistoryMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskHistoryUpdate) ClearTask() *TaskHistoryUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskHistoryUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := taskhistory.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.action": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.task"`)
	}
	return nil
}

func (_u *TaskHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskhistory.Table, taskhistory.Columns, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(taskhistory.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(taskhistory.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(taskhistory.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(taskhistory.FieldActor, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskHistoryUpdateOne is the builder for updating a single TaskHistory entity.
type TaskHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskHistoryMutation
}

// SetAction sets the "action" field.
func (_u *TaskHistoryUpdateOne) SetAction(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableAction(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *TaskHistoryUpdateOne) SetDetails(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableDetails(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *TaskHistoryUpdateOne) ClearDetails() *TaskHistoryUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetActor sets the "actor" field.
func (_u *TaskHistoryUpdateOne) SetActor(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableActor(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *TaskHistoryUpdateOne) SetTaskID(id int) *TaskHistoryUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskHistoryUpdateOne) SetTask(v *Task) *TaskHistoryUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_u *TaskHistoryUpdateOne) Mutation() *TaskHistoryMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskHistoryUpdateOne) ClearTask() *TaskHistoryUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the TaskHistoryUpdate builder.
func (_u *TaskHistoryUpdateOne) Where(ps ...predicate.TaskHistory) *TaskHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskHistoryUpdateOne) Select(field string, fields ...string) *TaskHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskHistory entity.
func (_u *TaskHistoryUpdateOne) Save(ctx context.Context) (*TaskHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskHistoryUpdateOne) SaveX(ctx context.Context) *TaskHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := taskhistory.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.action": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.task"`)
	}
	return nil
}

func (_u *TaskHistoryUpdateOne) sqlSave(ctx context.Context) (_node *TaskHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskhistory.Table, taskhistory.Columns, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskhistory.FieldID)
		for _, f := range fields {
			if !taskhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(taskhistory.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(taskhistory.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(taskhistory.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(taskhistory.FieldActor, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
