// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/tasktag"
)

// TaskTag is the model entity for the TaskTag schema.
type TaskTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskTagQuery when eager-loading is set.
	Edges        TaskTagEdges `json:"edges"`
	task_tags    *int
	selectValues sql.SelectValues
}

// TaskTagEdges holds the relations/edges for other nodes in the graph.
type TaskTagEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskTagEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasktag.FieldID:
			values[i] = new(sql.NullInt64)
		case tasktag.FieldKey, tasktag.FieldValue:
			values[i] = new(sql.NullString)
		case tasktag.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tasktag.ForeignKeys[0]: // task_tags
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskTag fields.
func (_m *TaskTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasktag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tasktag.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case tasktag.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case tasktag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tasktag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_tags", value)
			} else if value.Valid {
				_m.task_tags = new(int)
				*_m.task_tags = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the TaskTag.
// This includes values selected through modifiers, order, etc.
func (_m *TaskTag) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskTag entity.
func (_m *TaskTag) QueryTask() *TaskQuery {
	return NewTaskTagClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this TaskTag.
// Note that you need to call TaskTag.Unwrap() before calling this method if this TaskTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskTag) Update() *TaskTagUpdateOne {
	return NewTaskTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskTag) Unwrap() *TaskTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskTag) String() string {
	var builder strings.Builder
	builder.WriteString("TaskTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskTags is a parsable slice of TaskTag.
type TaskTags []*TaskTag
