// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/taskhistory"
)

// TaskHistory is the model entity for the TaskHistory schema.
type TaskHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Details holds the value of the "details" field.
	Details string `json:"details,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor string `json:"actor,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskHistoryQuery when eager-loading is set.
	Edges        TaskHistoryEdges `json:"edges"`
	task_history *int
	selectValues sql.SelectValues
}

// TaskHistoryEdges holds the relations/edges for other nodes in the graph.
type TaskHistoryEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskHistoryEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskhistory.FieldID:
			values[i] = new(sql.NullInt64)
		case taskhistory.FieldAction, taskhistory.FieldDetails, taskhistory.FieldActor:
			values[i] = new(sql.NullString)
		case taskhistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case taskhistory.ForeignKeys[0]: // task_history
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskHistory fields.
func (_m *TaskHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case taskhistory.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case taskhistory.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = value.String
			}
		case taskhistory.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = value.String
			}
		case taskhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case taskhistory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_history", value)
			} else if value.Valid {
				_m.task_history = new(int)
				*_m.task_history = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskHistory.
// This includes values selected through modifiers, order, etc.
func (_m *TaskHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskHistory entity.
func (_m *TaskHistory) QueryTask() *TaskQuery {
	return NewTaskHistoryClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this TaskHistory.
// Note that you need to call TaskHistory.Unwrap() before calling this method if this TaskHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskHistory) Update() *TaskHistoryUpdateOne {
	return NewTaskHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskHistory) Unwrap() *TaskHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskHistory) String() string {
	var builder strings.Builder
	builder.WriteString("TaskHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(_m.Details)
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(_m.Actor)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskHistories is a parsable slice of TaskHistory.
type TaskHistories []*TaskHistory
