// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/tasktag"
)

// TaskTagCreate is the builder for creating a TaskTag entity.
type TaskTagCreate struct {
	config
	mutation *TaskTagMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *TaskTagCreate) SetKey(v string) *TaskTagCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *TaskTagCreate) SetValue(v string) *TaskTagCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskTagCreate) SetCreatedAt(v time.Time) *TaskTagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskTagCreate) SetNillableCreatedAt(v *time.Time) *TaskTagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *TaskTagCreate) SetTaskID(id int) *TaskTagCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskTagCreate) SetTask(v *Task) *TaskTagCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the TaskTagMutation object of the builder.
func (_c *TaskTagCreate) Mutation() *TaskTagMutation {
	return _c.mutation
}

// Save creates the TaskTag in the database.
func (_c *TaskTagCreate) Save(ctx context.Context) (*TaskTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskTagCreate) SaveX(ctx context.Context) *TaskTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskTagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tasktag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskTagCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TaskTag.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := tasktag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TaskTag.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "TaskTag.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := tasktag.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "TaskTag.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskTag.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskTag.task"`)}
	}
	return nil
}

func (_c *TaskTagCreate) sqlSave(ctx context.Context) (*TaskTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskTagCreate) createSpec() (*TaskTag, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tasktag.Table, sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(tasktag.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(tasktag.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tasktag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tasktag.TaskTable,
			Columns: []string{tasktag.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_tags = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskTagCreateBulk is the builder for creating many TaskTag entities in bulk.
type TaskTagCreateBulk struct {
	config
	err      error
	builders []*TaskTagCreate
}

// Save creates the TaskTag entities in the database.
func (_c *TaskTagCreateBulk) Save(ctx context.Context) ([]*TaskTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskTagCreateBulk) SaveX(ctx context.Context) []*TaskTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
