// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/j0hnsmith/botTaskTracker/ent/predicate"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/tasktag"
)

// TaskTagUpdate is the builder for updating TaskTag entities.
type TaskTagUpdate struct {
	config
	hooks    []Hook
	mutation *TaskTagMutation
}

// Where appends a list predicates to the TaskTagUpdate builder.
func (_u *TaskTagUpdate) Where(ps ...predicate.TaskTag) *TaskTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *TaskTagUpdate) SetKey(v string) *TaskTagUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TaskTagUpdate) SetNillableKey(v *string) *TaskTagUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *TaskTagUpdate) SetValue(v string) *TaskTagUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *TaskTagUpdate) SetNillableValue(v *string) *TaskTagUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *TaskTagUpdate) SetTaskID(id int) *TaskTagUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskTagUpdate) SetTask(v *Task) *TaskTagUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskTagMutation object of the builder.
func (_u *TaskTagUpdate) Mutation() *TaskTagMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskTagUpdate) ClearTask() *TaskTagUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTagUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tasktag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TaskTag.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := tasktag.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "TaskTag.value": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskTag.task"`)
	}
	return nil
}

func (_u *TaskTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktag.Table, tasktag.Columns, sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tasktag.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(tasktag.FieldValue, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tasktag.TaskTable,
			Columns: []string{tasktag.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tasktag.TaskTable,
			Columns: []string{tasktag.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskTagUpdateOne is the builder for updating a single TaskTag entity.
type TaskTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskTagMutation
}

// SetKey sets the "key" field.
func (_u *TaskTagUpdateOne) SetKey(v string) *TaskTagUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TaskTagUpdateOne) SetNillableKey(v *string) *TaskTagUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *TaskTagUpdateOne) SetValue(v string) *TaskTagUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *TaskTagUpdateOne) SetNillableValue(v *string) *TaskTagUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *TaskTagUpdateOne) SetTaskID(id int) *TaskTagUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskTagUpdateOne) SetTask(v *Task) *TaskTagUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the TaskTagMutation object of the builder.
func (_u *TaskTagUpdateOne) Mutation() *TaskTagMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskTagUpdateOne) ClearTask() *TaskTagUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the TaskTagUpdate builder.
func (_u *TaskTagUpdateOne) Where(ps ...predicate.TaskTag) *TaskTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskTagUpdateOne) Select(field string, fields ...string) *TaskTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskTag entity.
func (_u *TaskTagUpdateOne) Save(ctx context.Context) (*TaskTag, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTagUpdateOne) SaveX(ctx context.Context) *TaskTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTagUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tasktag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TaskTag.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := tasktag.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "TaskTag.value": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskTag.task"`)
	}
	return nil
}

func (_u *TaskTagUpdateOne) sqlSave(ctx context.Context) (_node *TaskTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktag.Table, tasktag.Columns, sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasktag.FieldID)
		for _, f := range fields {
			if !tasktag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tasktag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tasktag.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(tasktag.FieldValue, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tasktag.TaskTable,
			Columns: []string{tasktag.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tasktag.TaskTable,
			Columns: []string{tasktag.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
