// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/j0hnsmith/botTaskTracker/ent/task"
	"github.com/j0hnsmith/botTaskTracker/ent/taskhistory"
)

// TaskHistoryCreate is the builder for creating a TaskHistory entity.
type TaskHistoryCreate struct {
	config
	mutation *TaskHistoryMutation
	hooks    []Hook
}

// SetAction sets the "action" field.
func (_c *TaskHistoryCreate) SetAction(v string) *TaskHistoryCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetDetails sets the "details" field.
func (_c *TaskHistoryCreate) SetDetails(v string) *TaskHistoryCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableDetails(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetDetails(*v)
	}
	return _c
}

// SetActor sets the "actor" field.
func (_c *TaskHistoryCreate) SetActor(v string) *TaskHistoryCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableActor(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskHistoryCreate) SetCreatedAt(v time.Time) *TaskHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableCreatedAt(v *time.Time) *TaskHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *TaskHistoryCreate) SetTaskID(id int) *TaskHistoryCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskHistoryCreate) SetTask(v *Task) *TaskHistoryCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_c *TaskHistoryCreate) Mutation() *TaskHistoryMutation {
	return _c.mutation
}

// Save creates the TaskHistory in the database.
func (_c *TaskHistoryCreate) Save(ctx context.Context) (*TaskHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskHistoryCreate) SaveX(ctx context.Context) *TaskHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskHistoryCreate) defaults() {
	if _, ok := _c.mutation.Actor(); !ok {
		v := taskhistory.DefaultActor
		_c.mutation.SetActor(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskHistoryCreate) check() error {
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "TaskHistory.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := taskhistory.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "TaskHistory.actor"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskHistory.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskHistory.task"`)}
	}
	return nil
}

func (_c *TaskHistoryCreate) sqlSave(ctx context.Context) (*TaskHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskHistoryCreate) createSpec() (*TaskHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskhistory.Table, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(taskhistory.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(taskhistory.FieldDetails, field.TypeString, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(taskhistory.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_history = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskHistoryCreateBulk is the builder for creating many TaskHistory entities in bulk.
type TaskHistoryCreateBulk struct {
	config
	err      error
	builders []*TaskHistoryCreate
}

// Save creates the TaskHistory entities in the database.
func (_c *TaskHistoryCreateBulk) Save(ctx context.Context) ([]*TaskHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskHistoryCreateBulk) SaveX(ctx context.Context) []*TaskHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
