// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskHistory is the predicate function for taskhistory builders.
type TaskHistory func(*sql.Selector)

// TaskTag is the predicate function for tasktag builders.
type TaskTag func(*sql.Selector)
